### PR TITLE
curly_brace_fix

### PR DESCRIPTION
**Pull request by R3D9477**

### CODE REVIEW

**Review by aleixq — CHANGES_REQUESTED** [review]
Well, A part from trimming the spaces it seems that line 145 also needs to be removed, if not two keys "name" will be there. If you can do this sure I'll approve. Thanks!

**Comment by R3D9477** [comment]
@aleixq sure

**Comment by R3D9477** [comment]
_(I don't know what differents between COM POrt and PORT)_

**Comment by mpictor** [comment]
It would be nice if someone would fix this up and merge. Like @r3d9u11 I don't know what should and shouldn't be in the file.

**Pull request closed without merging**
